kind: Service
apiVersion: v1
metadata: 
  name: monitor-project-lifecycle
  labels:
    app: monitor-project-lifecycle
spec: 
  selector: 
    app: monitor-project-lifecycle
  ports:
  - name: web
    protocol: TCP
    port: 8080
    targetPort: web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitor-project-lifecycle
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: monitor-project-lifecycle
        version: 1.0.0
    spec:
      containers:
      - name: monitor-project-lifecycle
        # This image setup is just for local development.
        image: openshift/origin-monitor-project-lifecycle
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
      resources:
        requests:
          memory: 4Mi
